---
# Exercise for setting up a Prometheus node_explorer in an EC
- name: Exercise for setting up a Prometheus node_explorer in an EC 
  # hosts: ubuntu
  # Use the public IP if the VM is already created
  hosts: all
  user: ubuntu
  become: true
  become_method: sudo
  become_user: root
  roles:
    - setup